USE SCHEMA ACMECO_SALES.RAW_DATA;

CREATE STAGE IF NOT EXISTS maven_stage
    COMMENT = 'Internal stage for Maven Analytics CSV files';ACMECO_SALES.RAW_DATA.SALES_PIPELINEACMECO_SALES.RAW_DATA.SALES_PIPELINE


